# tangram-layers
# SPDX-License-Identifier: MIT
# Copyright (c) vis.gl contributors

nodeLinker: node-modules

enableGlobalCache: true

approvedGitRepositories:
  - "https://github.com/tangrams/js-yaml.git"
  - "https://github.com/tangrams/topojson-client.git"
